CREATE TABLE users( 
id BIGSERIAL PRIMARY KEY, 
name VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
birthdate DATE NULL,
phone VARCHAR(80) NOT NULL UNIQUE,
home_address VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE, 
password VARCHAR(255) NOT NULL,
image VARCHAR(255) NULL, 
is_available BOOLEAN NULL,
session_token VARCHAR(255) NULL, 
created_at TIMESTAMP(0) NOT NULL, 
updated_at TIMESTAMP(0) NOT NULL
);